name: Solar System WorksFlow 
on:
  workflow_dispatch:
  push:
    branches:
        - main
        - 'feature/*'
env:
    MONGO_URI: mongodb+srv://supercluster.d83jj.mongodb.net/superData
    MONGO_USERNAME: superuser
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit-testing:
        name: Unit Testing
        strategy:
          matrix:
             nodejs_version: [20, 24, 26]
             operating_system: [ubuntu-latest, macos-latest]
             exclude:
              - nodejs_version: 26
                operating_system: macos-latest
              - nodejs_version: 26
                operating_system: ubuntu-latest
              - nodejs_version: 24
                operating_system: macos-latest
        runs-on: ${{ matrix.operating_system }}
        steps:
        - name: checkout Repository
          uses: actions/checkout@v4
        
        - name: Setup NodeJS Version - ${{ matrix.nodejs_version }}
          uses: actions/setup-node@v6
          with:
            node-version: ${{ matrix.nodejs_version }}
        - name: Cache NPM Dependencies
          uses: actions/cache@v3
          with:
            path: node_modules
            key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

        - name: Install Dependencies
          run: npm install

        - name: Unit Testing
          run: npm test

        - name: Archive Test Results
          uses: actions/upload-artifact@v6
          with:
            name: Mocha-Test-Results
            path: test-results.xml
            overwrite: true

    code-coverage:
        name: Code Coverage
        runs-on: ubuntu-latest
        steps:
        - name: checkout Registry
          uses: actions/checkout@v6
        - name: Setup NodeJS version - 22
          uses: actions/setup-node@v3
          with:
            node-version: 20
        - name: Cache NPM Dependencies
          uses: actions/cache@v3
          with:
            path: node_modules
            key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
        - name: Install Dependencies
          run: npm install
        - name: Check Code Coverage
          continue-on-error: true
          run: npm run coverage
        - name: Archive Test Results
          uses: actions/upload-artifact@v7
          with:
            name: Code-coverage-Results
            path: coverage
            retention-days: 5 
